python_cms/blueprints/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from os import environ
import requests
from oauthlib.oauth2 import WebApplicationClient
import json
from python_cms.models.user import UserModel
from flask_login import login_user, logout_user

auth_blueprint = Blueprint('auth', __name__)

GOOGLE_CLIENT_ID = environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = environ.get('GOOGLE_CLIENT_SECRET')

GOOGLE_DISCOVERY_URL = (
    "https://accounts.google.com/.well-known/openid-configuration")

client = WebApplicationClient(GOOGLE_CLIENT_ID)


@auth_blueprint.route('/login')
def login():
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  authorization_endpoint = google_provider_cfg["authorization_endpoint"]
  request_uri = client.prepare_request_uri(
      authorization_endpoint,
      redirect_uri=request.host_url + "authorize",
      scope=["openid", "email", "profile"])

  print(request_uri)

  # this redirect will take user to google login page
  return redirect(request_uri)


# this is the callback route that google will redirect to after login
@auth_blueprint.route('/authorize')
def authorize():
  code = request.args.get("code")
  google_provider_cfg = requests.get(GOOGLE_DISCOVERY_URL).json()
  token_endpoint = google_provider_cfg["token_endpoint"]
  token_url, headers, body = client.prepare_token_request(
      token_endpoint,
      authorization_response=request.url,
      redirect_url=request.base_url,
      code=code)
  token_response = requests.post(token_url,
                                 headers=headers,
                                 data=body,
                                 auth=(GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET))

  print(token_response.json())

  client.parse_request_body_response(json.dumps(token_response.json()))

  # now we have the token, we can get the user info
  userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
  uri, headers, body = client.add_token(userinfo_endpoint)
  userinfo_response = requests.get(uri, headers=headers)

  print(userinfo_response.json())

  if userinfo_response.json().get("email_verified"):
    unique_id = userinfo_response.json()["sub"]
    users_email = userinfo_response.json()["email"]
    picture = userinfo_response.json()["picture"]
    users_name = userinfo_response.json()["name"]
    user = UserModel(id=unique_id,
                     name=users_name,
                     email=users_email,
                     picture=picture)

    # if the user doesn't exist, create a new one
    if not UserModel.get(unique_id):
      user.save()

    # begin user session by logging in the user
    login_user(user)

    return redirect(url_for('pages.index'))

  return "User email not available or not verified by Google.", 400


@auth_blueprint.route('/logout')
def logout():
  logout_user()
  return redirect(url_for('pages.index'))

python_cms/blueprints/pages.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_from_directory
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from python_cms.forms.post_form import PostForm
import python_cms
from os import path
from bs4 import BeautifulSoup
from flask_ckeditor import upload_success, upload_fail

from python_cms.models.post import PostModel

pages_blueprint = Blueprint('pages', __name__)

VALID_TAGS = [
    'div', 'br', 'p', 'h1', 'h2', 'img', 'h3', 'ul', 'li', 'em', 'strong', 'a',
    'blockquote'
]


def sanitize_html(value):
  soup = BeautifulSoup(value, features="html.parser")
  for tag in soup.findAll(True):
    if tag.name not in VALID_TAGS:
      tag.extract()

  return soup.renderContents()


@pages_blueprint.route('/')
def index():
  posts = PostModel.get_all()
  for post in posts:
    if type(post.body) == bytes:
      post.body = post.body.decode('utf-8')
    if type(post.title) == bytes:
      post.title = post.title.decode('utf-8')
  return render_template('index.html.j2', posts=posts)


@pages_blueprint.route('/files/<path:filename>')
def files(filename):
  directory = path.join(python_cms.ROOT_PATH, 'files_upload')
  return send_from_directory(directory=directory, path=filename)


@pages_blueprint.route('/post/<int:post_id>')
def post(post_id):
  post = PostModel.get(post_id)
  post.body = post.body.decode('utf-8')
  post.title = post.title.decode('utf-8')
  if not post:
    return "post not found", 404
  return render_template('post.html.j2', post=post)


@pages_blueprint.route('/about')
def about():
  return render_template('about.html.j2')


@pages_blueprint.route('/add', methods=['GET', 'POST'])
@login_required
def create_post():
  form = PostForm()
  if request.method == 'POST' and form.validate_on_submit():
    title = request.form['title']
    body = request.form['body']
    user = current_user.get_id()
    clean_title = sanitize_html(title)
    clean_body = sanitize_html(body)

    file = request.files['teaser_image']
    print(file)
    filename = secure_filename(file.filename)
    file.save(path.join(python_cms.ROOT_PATH, 'files_upload', filename))

    post = PostModel(title=clean_title,
                     body=clean_body,
                     user_id=user,
                     teaser_image=filename)
    post.save()
    flash(f'Post {title} created successfully', 'success')
    print(request.form)
    return redirect(url_for('pages.create_post'))
  print(form.errors)

  return render_template('create_post.html.j2', form=form)


@pages_blueprint.route('/upload', methods=['POST'])
def upload():
  f = request.files['upload']
  extension = f.filename.split('.')[-1].lower()
  if extension not in ['jpg', 'gif', 'png', 'jpeg']:
    return upload_fail(message="File extension not allowed")
  directory = path.join(python_cms.ROOT_PATH, 'files_upload')
  filename = secure_filename(f.filename)
  f.save(path.join(directory, filename))
  url = url_for('pages.files', filename=filename)

  return upload_success(url=url, filename=filename)

python_cms/templates/about.html.j2
{% extends "base.html.j2" %}
{% block title %} About page {% endblock %}
{% block content %}
    <h1>About page</h1>
{% endblock %}

python_cms/templates/base.html.j2
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% block headsource %} {% endblock %}
  </head>
  <body>
    <header class="navbar">
      <section class="navbar-section">
        <a href="{{ url_for('pages.index') }}" class="navbar-brand mr-2">Home</a>
        <a href="{{ url_for('pages.about') }}" class="btn btn-link">About</a>
      </section>
      <section class="navbar-section">
        {% if current_user.is_authenticated %}
          <div class="chip user-menu">
            <img src="{{current_user.profile_pic}}" class="avatar avatar-sm" alt="">
            {{ current_user.name }}
            <div class="user-submenu">
              <a href="{{ url_for('pages.create_post') }}" >Create Post</a>
              <a href="{{ url_for('auth.logout') }}" >Log out</a>
            </div>
          </div>
        {% else %}
          <a href="{{ url_for('auth.login') }}" class="btn btn-link">Log in</a>
        {% endif %}
      </section>
    </header>
    <main>
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

python_cms/templates/create_post.html.j2
{% extends "base.html.j2" %}
{% block title %} Create post {% endblock %}
{% block headsource %} {{ ckeditor.load() }} {% endblock %}
{% block content %} 
  <h1>Create post</h1>
  
  {% for message in get_flashed_messages() %}
    <div class="toast toast-success">
      <button class="btn btn-clear float-right"></button>
      {{ message }}
    </div>
  {% endfor %}


  <form action="/add" method="POST" class="form-group" enctype="multipart/form-data">
    {{ form.csrf_token() }}
    <label for="title">{{ form.title.label }}</label>
    {{form.title(class="form-input", placeholder="title")}}
    <label for="teaser_image">{{ form.teaser_image.label }}</label>
    {{form.teaser_image(class="form-input")}}
    <label for="body">{{ form.body.label }}</label>
    {{form.body(class="form-input", placeholder="your article goes here", id="body")}}
    {{form.submit(class="btn btn-primary input-group-btn float-right")}}
    {{ ckeditor.config(name="body") }}
  </form>
{% endblock %}

python_cms/templates/index.html.j2
{% extends "base.html.j2" %}
{% block title %} Hello World {% endblock %}
{% block content %}
  {% if posts|length == 0 %}
    <h1> No posts yet </h1>
  {% else %}
    <div class="columns">
      {% for post in posts %}
        <div class="column col-6 col-md-12">
        <div class="card article-card">
          <div class="card-image">
            <img src="/files/{{post.teaser_image}}" class="img-responsive article-image" alt="">
          </div>
          <div class="card-header">
            <div class="card-title h5">{{ post.title }}</div>
          </div>
          <div class="card-footer">
            <a class="btn btn-primary" href="/post/{{ post.id }}">Read More</a>
          </div>
        </div>
      </div>
      {% endfor %}
      </div>
  {% endif %}
{% endblock %}

python_cms/templates/post.html.j2
{% extends "base.html.j2" %}
{% block title %} Hello World {% endblock %}
{% block content %}
  {% if post.id is not defined %}
    <h1>Post not found</h1>
  {% else %}
  <h1>{{ post.title }}</h1>
  <img src="/files/{{post.teaser_image}}" class="img-responsive article-image-inner" alt="">
  {{ post.body|safe }}
  {% endif %}
{% endblock %}